---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Chirpy
  description: Simple social media CRUD (Create, Read, Update, Delete)
tags:
  - name: account
    description: Account functions
  - name: chirp
    description: Posts with text by an author
paths:
  /api/signup:
    post:
      tags:
        - account
      summary: Creates a chirpy account
      consumes:
        - application/json
      parameters:
        - in: header
          name: email
          description: Account email
          type: string
          required: true
        - in: header
          name: password
          description: Account password
          type: string
          required: true
      responses:
        '200':
          description: Created the account
        '400':
          description: Failed to Create account
  /chirps:
    post:
      tags:
        - chirp
      summary: Creates a chirp
      consumes:
        - application/json
      requestBody:
        description: Create a new chirp
        content:
          application/json:
            schema:
              type: object
              properties:
                chirpBody:
                  type: string
              required:
                - body
            style: form
      responses:
        '200':
          description: Posted the chirp
        '400':
          description: Failed to post the chirp
        '401':
          description: Unauthorized to post chirps
      security:
        - chirp_auth:
          - write:chirps
    get:
      tags:
        - chirp
      summary: Gets 10 newest chirps
      consumes:
        - application/json
      responses:
        '200':
          description: Got the chirps
        '400':
          description: Failed to get chirps
      security:
        - chirp_auth:
          - write:chirps
  /chirps/{chirpId}:
    put:
      tags:
        - chirp
      summary: Updates a chirp
      consumes:
        - application/json
      parameters:
        - name: chirpId
          in: path
          description: ID of the chirp to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Updates a new chirp
        content:
          application/json:
            schema:
              type: object
              properties:
                chirpBody:
                  type: string
              required:
                - body
            style: form
      responses:
        '200':
          description: Updated the chirp
        '400':
          description: Failed to update the chirp
      security:
        - chirp_auth:
          - write:chirps
    delete:
      tags:
        - chirp
      summary: Deletes a chirp
      consumes:
        - application/json
      operationId: deleteChirp
      parameters:
        - name: chirpId
          in: path
          description: Pet id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted the chirp
        '400':
          description: Failed to delete the chirp
      security:
        - chirp_auth:
          - write:chirps
components:
  securitySchemes:
    chirp_auth:
      type: oauth2
      flows:
        password:
          tokenUrl: http://localhost:8000/oauth/token
          scopes:
            write:chirps: create and modify chirps by your account
            read:chirps: read chirps
    api_key:
      type: apiKey
      name: api_key
      in: header