---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Chirpy
  description: Simple social media CRUD
tags:
  - name: signup
    description: Create an account
  - name: chirps
    description: Posts with text by an author
paths:
  /api/signup:
    post:
      tags:
        - signup
      consumes:
        - application/json
      parameters:
        - in: header
          name: email
          description: Account email
          type: string
          required: true
        - in: header
          name: password
          description: Account password
          type: string
          required: true
      responses:
        '200':
          description: Created the account
        '400':
          description: Failed to Create chirp
  /api/chirps:
    post:
      tags:
        - chirps
      responses:
        '200':
          description: Create a chirp
        '400':
          description: Failed to Create chirp
components:
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        password:
          tokenUrl: http://localhost:8000/oauth/token
          scopes:
            write:chirps: create and modify chirps by your account
            read:chirps: read chirps
    api_key:
      type: apiKey
      name: api_key
      in: header